using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class EnemyPatrol : MonoBehaviour
{
    public float speed;
    public float rayDistance;
    private bool isMovingRight = true;
    public transform groundDetection;

    // Update is called once per frame
    void Update()
    {
        transform.Translate(Vector2.right * speed * Time.deltaTime);
        RaycastHit2D groundInfo = Physics2D.RayCast(groundDetection.position, vector2.down, rayDistance);
        if(groundInfo.collider == false)
        {
            if(isMovingRight == true)
            {
                transform.eulerAngles = new Vector3(0, -180, 0);
                isMovingRight = false;
            }
            else
            {
                transform.eulerAngles  new Vector3(0, 0, 0);
                isMovingRight = true;
            }
        }
    }
}
